export enum PermissionEnum {
  All = "All",
  None = "None",
  Mint = "Mint",
  ViewDashboard = "View Dashboard",
  ViewDrug = "View Drug",
  ApproveDrug = "Approve Drug",
  DeclineDrug = "Decline Drug",
  RequestApproval = "Request Approval",
  MarkAsManufactured = "Mark as Manufactured",
  MarkAsInTransitToDistributer = "Mark as In Transit to Distributer",
  MarkAsInDistributerFacility = "Mark as In Distributer Facility",
  MarkAsInTransitToWholesaler = "Mark as In Transit to Wholesaler",
  MarkAsDeliveredToWholesaler = "Mark as Delivered to Wholesaler",
  MarkAsInWholesalerWarehouse = "Mark as In Wholesaler Warehouse",
  MarkAsReadyForSale = "Mark as Ready for Sale",
  MarkAsSold = "Mark as Sold",
  RegisterManufacturer = "Register Manufacturer",
  RegisterRegulatoryAgency = "Register Regulatory Agency",
  RegisterDistributer = "Register Distributer",
  RegisterWholesaler = "Register Wholesaler",
}
